services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "3000:80"
  
  backend:
    image: backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "3001:8080"